# Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.1


### Creating tensors with `tf.constant`

In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scaler.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [9]:
matrix = tf.constant([
    [10, 7],
    [7, 10]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [19]:
tensor = tf.constant([
    [[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]],
    [[13, 14, 15],
    [16, 17, 18]]
])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [21]:
tensor.ndim

3

### Creating tensors with `tf.variable`

In [22]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [26]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [27]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [32]:
tf.random.uniform((1, 2))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.6396836, 0.7565217]], dtype=float32)>

In [34]:
tf.random.Generator.from_seed(42).normal((3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [35]:
tf.random.Generator.from_seed(42).normal((3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

*Shuffle order of elements*

In [68]:
# Both global and operational random seeds are required for reproducible results
tf.random.set_seed(42)
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

### Creating tensors with numpy arrays

In [71]:
tf.ones((10, 10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [72]:
tf.zeros((10, 10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

The main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU - thereby having faster overall computing

In [75]:
import numpy as np
np_arr = np.arange(1, 25)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [77]:
# Capital letters for matrices/tensors; simple letters for vectors
A = tf.constant(np_arr)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [79]:
tf.constant(np_arr, shape=(2, 4, 4))

TypeError: Eager execution of tf.constant with unsupported shape. Tensor [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (converted from [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]) has 24 elements, but got `shape` (2, 4, 4) with 32 elements).

In [80]:
tf.constant(np_arr, shape=(2, 4, 3))

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [85]:
A, A.numpy()

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]))

In [94]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [95]:
tensor.dtype

tf.int32

In [97]:
tensor.ndim

3

In [98]:
tensor.shape

TensorShape([3, 2, 3])

In [100]:
tf.size(tensor).numpy()

18

In [114]:
tf.expand_dims(tensor, axis=0)

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]]])>

### Manipulating tensors

*Basic operations & matrix multiplication*

In [118]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [119]:
tensor + 3

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])>

In [120]:
tf.add(tensor, 3)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])>

In [121]:
# tensorflow operations are faster than the basic one
tf.multiply(tensor, 2)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]],

       [[26, 28, 30],
        [32, 34, 36]]])>

In [122]:
tensor * 2

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]],

       [[26, 28, 30],
        [32, 34, 36]]])>

In [134]:
tensor_a = tf.constant([
    [1, 2],
    [3, 4]
])

tensor_b = tf.constant([
    [3, 3],
    [4, 5]
])

tensor_c = tf.constant([
    [3, 3, 4],
    [4, 5, 6],
])

tf.matmul(tensor_a, tensor_b), tf.matmul(tensor_a, tensor_c)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 13],
        [25, 29]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 13, 16],
        [25, 29, 36]])>)

In [131]:
tf.multiply(tensor_a, tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [12, 16]])>

In [136]:
tensor_d = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

tf.matmul(tensor_a, tensor_d)

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [3,2] [Op:MatMul]

In [139]:
tf.matmul(tensor_a, tf.reshape(tensor_d, (2, 3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33]])>

In [142]:
tf.matmul(tensor_a, tf.transpose(tensor_d))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39]])>

In [145]:
tf.tensordot(tensor_a, tf.transpose(tensor_d), axes=0)

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  3,  5],
         [ 2,  4,  6]],

        [[ 2,  6, 10],
         [ 4,  8, 12]]],


       [[[ 3,  9, 15],
         [ 6, 12, 18]],

        [[ 4, 12, 20],
         [ 8, 16, 24]]]])>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you'll transpose one of the tensors (rather than reshaping) to satisfy the matrix multiplication rules

*Changing datatype of tensors*

In [148]:
tensor_dtype = tf.constant([1, 2, 3.2])

In [149]:
tensor_dtype.dtype

tf.float32

In [152]:
tf.dtypes.cast(tensor_dtype, tf.dtypes.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.        , 2.        , 3.20000005])>

In [154]:
tensor_dtype = tf.dtypes.cast(tensor_dtype, tf.dtypes.float64)

In [155]:
tensor_dtype.dtype

tf.float64

In [156]:
tensor_dtype

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.        , 2.        , 3.20000005])>

In [157]:
tensor_dtype = tf.dtypes.cast(tensor_dtype, tf.dtypes.int32)

In [158]:
tensor_dtype

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [159]:
tensor_dtype = tf.dtypes.cast(tensor_dtype, tf.dtypes.float16)

In [160]:
tensor_dtype

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

**Modern accelerators can run faster operations in the 16-bit dtypes**

*Aggregation (min, max, mean, etc...)*

In [162]:
tf.abs(tensor)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [171]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [172]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [173]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [174]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=171>

In [178]:
tf.math.reduce_variance(tensor)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.

In [177]:
tf.math.reduce_variance(tf.dtypes.cast(tensor, tf.dtypes.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=26.92>

In [179]:
tf.math.reduce_std(tf.dtypes.cast(tensor, tf.dtypes.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=5.188>

In [182]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [187]:
arg_tensor = tf.random.uniform((50,))
arg_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [188]:
tf.argmax(arg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [189]:
tf.argmin(arg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [192]:
arg_tensor[tf.argmax(arg_tensor)], arg_tensor[tf.argmin(arg_tensor)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9869994>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.013772249>)